### ISSUE TITLE
Problem related to the Blackbody module in astropy 4.3.1

### ISSUE THREAD

**Issue by viveikjha** [legolason/PyQSOFit#20]
While running pyQSOFIT today I encountered an error related to astropy when importing the 'blackbody' model. 
I had recently upgraded the astropy module to 4.3.1. I searched the astropy documentation but have not found the 'blackbody_lambda" module so far...although the 'Blackbody' module is there. I am just putting it here in case anyone else is encountering the same problem...

 The error is attached below. I have not been able to solve it so far. Any help will be really appreciated.

`Traceback (most recent call last):
  File "fit_the_spectrum.py", line 10, in <module>
    from PyQSOFit import QSOFit,manygauss,onegauss
  File "/home/vivek/workhub/asymmetry-work/PyQSOFit.py", line 19, in <module>
    from astropy.modeling.blackbody import blackbody_lambda
ModuleNotFoundError: No module named 'astropy.modeling.blackbody'`

**Comment by viveikjha** [comment]
An update:
I found some information here regarding the depreciation of this module. 
https://astropy-astrofrog.readthedocs.io/en/latest/modeling/blackbody_deprecated.html

However, I'm not sure how to implement it in the code correctly.
 @legolason if you can help me with that it'll be great.

**Comment by legolason** [comment]
Hi viveikjha,

You already found the right solution, you just need to use the new function to replace the old one, P[1] is the temperature, 
It should be something like this, I have not tested it, 

from astropy.modeling.models import BlackBody
blackbody_lambda(xval, pp[1]).value -->
bb_lam = BlackBody(pp[1], scale=1.0 * u.erg / (u.cm ** 2 * u.AA * u.s * u.sr))
bbflux = bb_lam(xval).value*3.14

**Comment by ParyagSharma** [comment]
I also encountered the same issue faced by @viveikjha . Following the suggestion of @legolason, we did the following changes:
importing the modules:
`from astropy import units as u` 
`from astropy.modeling.physical_models import BlackBody`


and modified the code segment accordingly:
`bb_lam = BlackBody(pp[1]*u.K, scale=1.0 * u.erg / (u.cm ** 2 * u.AA * u.s * u.sr))
        bbflux = bb_lam(xval).value*3.14`

Now the code is working fine.
